name: reaction
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - sympy
  - ipykernel
  - jupyterlab
  - pytorch=2.4.0
  - cudatoolkit=12.4
  - pytorch-lightning
  - pytorch-geometric
  - tensorboard
  - wandb
  - pip
  - seaborn
  - ray
  - optuna
  - "ray[tune]"
  - pip:
      - torch-scatter
      - torch-sparse
      - torch-cluster
      - torch-spline-conv
      - torch-geometric
